const message = {
    AUTH_FAILED:"AUTHENTICATION FAILED.",
    BAD_REQUEST:"BAD REQUEST.",
    NOT_FOUND:"NOT FOUND.",
    EMPTY_FIELD:"FIELD SHOULD NOT EMPTY.",
    ALREADY_REGISTERED:"USER ALREADY REGISTERED.",
    REGISTER_SUCCESS:"SIGN-UP SUCCESSFULLY.",
    SENDING_LINK:"User Not Verified.Sending link to your email please verify.",
    OTP_SENT:"OTP SENT TO YOUR REGISTERED EMAIL.",
    LOGIN_SUCCESS:"LOGIN SUCCESSFULLY.",
    LOGIN_FAILED:"LOGIN FAILED ❌❌.",
    TOKEN_EXPIRED:"TOKEN EXPIRED.",
    OTP_EXPIRED:"OTP EXPIRED.",
    INVALID_URL:"INVALID URL.",
    USER_UPDATE:"USER UPDATED SUCCESSFULLY.",
    EMAIL_UPDATE:"EMAIL UPDATED SUCCESSFULLY.",
    PASSWORD_UPDATE:"YOUR PASSWORD HAS BEEN UPDATED.",
    PASSWORD_MISMATCH:"PASSWORD MISMATCH.",
    PASSWORD_SAME:"PASSWORD MUST BE DIFFERENT FROM OLD PASSWORD.",
    VERIFIED_SUCCESS:"VERIFIED SUCCESSFULLY.",
    PROJECT_CREATE:"PROJECT CREATED SUCCESSFULLY.",
    PROJECT_UPDATE:"PROJECT UPDATED SUCCESSFULLY.",
    PROJECT_DELETE:"PROJECT DELETED SUCCESSFULLY.",
    TASK_CREATE:"TASK CREATED SUCCESSFULLY.",
    TASK_UPDATE:"TASK UPDATED SUCCESSFULLY.",
    TASK_DELETE:"TASK DELETED SUCCESSFULLY."
}

export { message };